In [1]:
%%capture

from pandas import ExcelWriter
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"


from staticV22.agyw import AgywPrev

# 3 eme  semaine de decembre!

In [2]:
%%capture
datim = AgywPrev()

In [3]:
datim.data_dreams_valid
datim.total_datim_general
df = datim.data_dreams_valid

,id_patient,id_parenting_group,departement,commune,nbre_pres_for_inter,nbre_parenting_coupe_present,has_comdom_topic,has_preventive_vbg,number_of_condoms_sensibilize,number_condoms_sensibilization_date_in_the_interval,...,socioeco_app,prep,contraceptive,ps_1014,ps_1519,ps_2024,primary_only,primary_and_OneSecondary_services,completed_one_service,has_started_one_service
226,75394,3363.0,Nord,Milot,21,10,yes,yes,0,0,...,yes,no,no,no,primary,no,invalid,full_primary_leastOneSecondary,invalid,no
227,75395,NaN,Nord,Milot,21,0,yes,yes,0,0,...,yes,no,no,no,primary,no,invalid,full_primary_leastOneSecondary,invalid,no
244,75528,NaN,Nord,Cap-Haïtien,17,0,yes,yes,1,0,...,yes,no,no,no,primary,no,invalid,full_primary_leastOneSecondary,invalid,no
275,75987,NaN,Artibonite,Dessalines,17,0,yes,yes,1,0,...,yes,no,no,no,primary,no,invalid,full_primary_leastOneSecondary,invalid,no
287,75964,NaN,Artibonite,Liancourt,17,0,yes,yes,0,0,...,yes,no,no,no,no,primary,invalid,full_primary_leastOneSecondary,invalid,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35392,100543,NaN,Nord,Cap-Haïtien,0,0,no,None,0,0,...,yes,no,no,no,no,no,invalid,invalid,primary_part_services,no
35393,101428,NaN,Nord,Milot,0,0,no,None,0,0,...,yes,no,no,no,no,no,invalid,invalid,primary_part_services,no
35394,105142,NaN,Nord,Cap-Haïtien,0,0,no,None,0,0,...,yes,no,no,no,no,no,invalid,invalid,primary_part_services,no
35395,105158,NaN,Nord,Cap-Haïtien,0,0,no,None,0,0,...,yes,no,no,no,no,no,invalid,invalid,primary_part_services,no
35396,105341,NaN,Nord,Cap-Haïtien,0,0,no,None,0,0,...,yes,no,no,no,no,no,invalid,invalid,primary_part_services,no

2267

In [4]:
df_sample  = df.sample(frac=0.1,random_state=1)
df_sample

,id_patient,id_parenting_group,departement,commune,nbre_pres_for_inter,nbre_parenting_coupe_present,has_comdom_topic,has_preventive_vbg,number_of_condoms_sensibilize,number_condoms_sensibilization_date_in_the_interval,...,socioeco_app,prep,contraceptive,ps_1014,ps_1519,ps_2024,primary_only,primary_and_OneSecondary_services,completed_one_service,has_started_one_service
9854,132624,NaN,Nord,Cap-Haïtien,16,0,yes,yes,1,1,...,no,no,no,no,no,no,invalid,invalid,primary_part_services,no
2286,83458,NaN,Artibonite,Liancourt,17,0,yes,yes,0,0,...,yes,no,no,no,primary,no,invalid,full_primary_leastOneSecondary,invalid,no
9785,132539,NaN,Nord,Plaine-du-Nord,18,0,yes,yes,1,1,...,no,no,no,no,no,primary,full_primary_only,invalid,invalid,no
18135,94052,NaN,Artibonite,Desdunes,21,0,yes,yes,1,0,...,no,no,no,no,primary,no,full_primary_only,invalid,invalid,no
9605,87863,NaN,Nord,Plaine-du-Nord,21,0,yes,yes,1,1,...,no,no,no,primary,no,no,invalid,full_primary_leastOneSecondary,invalid,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6163,109931,NaN,Ouest,Kenscoff,16,0,yes,yes,2,1,...,no,no,no,no,no,no,invalid,invalid,primary_part_services,no
34770,131774,NaN,Ouest,Kenscoff,21,0,yes,yes,0,0,...,no,no,no,primary,no,no,invalid,full_primary_leastOneSecondary,invalid,no
2616,94313,NaN,Artibonite,Desdunes,21,0,yes,yes,0,0,...,no,no,no,primary,no,no,invalid,full_primary_leastOneSecondary,invalid,no
34848,131855,NaN,Ouest,Kenscoff,21,0,yes,yes,0,0,...,no,no,no,primary,no,no,invalid,full_primary_leastOneSecondary,invalid,no
4164,82725,NaN,Artibonite,Desdunes,17,0,yes,yes,0,0,...,yes,no,no,no,no,primary,invalid,full_primary_leastOneSecondary,invalid,no

In [5]:
resume_sample = df_sample.pivot_table(values="id_patient",index='age_range',columns='departement',aggfunc='count',fill_value=0,margins=True,margins_name="Total")
resume_sample

departement  Artibonite  Nord  Ouest  Total
age_range
10-14                25    12     31     68
15-19                35    14     42     91
20-24                35    16     17     68
Total                95    42     90    227

In [6]:
artibonites = df_sample[df_sample.departement == "Artibonite"]
nord = df_sample[df_sample.departement == "Nord"]
ouest = df_sample[df_sample.departement == "Ouest"]

artibonites.id_patient.count()
nord.id_patient.count()
ouest.id_patient.count()

95

42

90

In [7]:
sampling = ExcelWriter("echantillon_Q1FY22_december.xlsx",engine="xlsxwriter")
#sampling = ExcelWriter("echantillon_Q1FY22.xlsx",engine="xlsxwriter")
resume_sample.to_excel(sampling,sheet_name="Tableau Resume", index=True)
artibonites.to_excel(sampling,sheet_name="Artibonite", index=False, na_rep="")
nord.to_excel(sampling,sheet_name="Nord", index=False, na_rep="")
ouest.to_excel(sampling,sheet_name="Ouest", index=False, na_rep="")
sampling.save()

In [8]:
df_sample.pivot_table(values="id_patient",index='age_range',columns='curriculum_detailed',aggfunc='count',fill_value=0,margins=True,margins_name="Total")

curriculum_detailed  has_started  no  yes  Total
age_range
10-14                         10   0   58     68
15-19                         11   1   79     91
20-24                          7   2   59     68
Total                         28   3  196    227